### ISSUE TITLE
Add prereq "use case" to narrative prior to use case table

### ISSUE THREAD

**Issue by ashleysa** [force11/force11-scwg#130]
Summary of discussion a little before noon on Sunday of workshop:
Ensure there is an introduction to the "zero" use case in the narrative introduction to the use cases table. This prerequisite is that a "creator" has generated a piece of software that has metadata. Then the rest of the use cases follow, but we need to clarify that the software has been generated.

**Comment by wakibbe** [comment]
We need to be able to handle citation examples where the creator does not have a citable object and has no current incentive to create a citable object. RRID is a natural place for creating citable objects that are not otherwise citable. Citing SPSS is a possible example: https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/f5aaa1cd-f636-52e4-97fd-26ad0fa8816b/search?q=spss

**Comment by kyleniemeyer** [comment]
OK, I added some text in a929e6983e9c67071ecced60cc9a35f4d83448b6 addressing this issue, so I'm going to mark this as "to be closed" unless anyone objects to my addition. If you do want it to be different, please suggest specific changes or submit a PR.
