### ISSUE TITLE
DOIs vs landing pages

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#144]
Do we need to say that DOIs point to landing pages with metadata and a link to software, not directly to software?

**Comment by arfon** [comment]
Errr, I don't think so? Is http://dx.doi.org/10.5281/zenodo.49771 an example of a 'landing page with metadata and a link to software'?

**Comment by danielskatz** [comment]
Yes.  My thought, based on a comment at the Software and Data Citation workshop yesterday, is that the principles could currently be read to say that the identifiers should point to the software directly, such as a URL to a github repo.  I don't think this is what we want.

**Comment by arfon** [comment]
> Yes. My thought, based on a comment at the Software and Data Citation workshop yesterday, is that the principles could currently be read to say that the identifiers should point to the software directly, such as a URL to a github repo. I don't think this is what we want.

I'm not sure that I understand why pointing to a GitHub repository directly would be a bad idea (aside from the concern about archiving/longevity). Was there discussion why we _wouldn't_ want this?

**Comment by timclark** [comment]
Hi Arfon,

What we say in data citation is that you should not point to a dataset directly from the citation, you should point to a landing page.

Landing page will have metadata that describes the data set or sets, provides its machine readable standard citation, tells you about its size, data license and access restrictions/conditions/terms of use if any, embargo status if any, and if dataset has been de-accessioned the landing page remains in place retaining the metadata after the data goes away & indicates de-accessioning status.

Tim

---

Timothy Clark, Ph.D.
Assistant Professor of Neurology, Harvard Medical School
Director of Informatics, MassGeneral Institute for Neurodegenerative Disease
Computer Scientist, Massachusetts General Hospital
co-Director, Data and Statistics Core, Massachusetts Alzheimer Disease Research Center
website: http://mindinformatics.orghttp://mindinformatics.org/ mobile: +1 617-947-7098 fax: +1 617-213-5418
ORCID ID: 0000-0003-4060-7360

On Jun 8, 2016, at 9:51 AM, Arfon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes. My thought, based on a comment at the Software and Data Citation workshop yesterday, is that the principles could currently be read to say that the identifiers should point to the software directly, such as a URL to a github repo. I don't think this is what we want.

I'm not sure that I understand why pointing to a GitHub repository directly would be a bad idea (aside from the concern about archiving/longevity). Was there discussion why we wouldn't want this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHubhttps://github.com/force11/force11-scwg/issues/144#issuecomment-224595141, or mute the threadhttps://github.com/notifications/unsubscribe/AGT3jwsn6praaBu_EgXRHZ1iUpfaKgcKks5qJsj7gaJpZM4IwPN0.

The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by danielskatz** [comment]
This was exactly my thought.  The concern is archiving/longevity.

We say:

(4) Persistence: Unique identifiers and metadata describing the software and its disposition should persist – even beyond the lifespan of the software they describe.
(5) Accessibility: Software citations should permit and facilitate access to the software itself and to its associated metadata, documentation, data, and other materials necessary for both humans and machines to make informed use of the referenced software.
(6) Specificity: Software citations should facilitate identification of, and access to, the specific version of software that was used. Software identification should be as specific as necessary, such as using version numbers, revision numbers, or variants such as platforms.

Given this, I would like to add something to the discussion that roughly corresponds with the data language Tim mentioned.

@kyleniemeyer, can you add this to the discussion document that contains the community feedback so we can track this?

**Comment by kyleniemeyer** [comment]
@danielskatz will do! I have all the feedback collected in a document, just need to clean it up a bit.

**Comment by arfon** [comment]
> Landing page will have metadata that describes the data set or sets, provides its machine readable standard citation, tells you about its size, data license and access restrictions/conditions/terms of use if any, embargo status if any, and if dataset has been de-accessioned the landing page remains in place retaining the metadata after the data goes away & indicates de-accessioning status.

👍 thanks @timclark. So in theory, if a repository host such as GitHub offered some guarantee of archiving/longevity then it would potentially meet the rest of the criteria?

BTW, I'm not asking these questions to be difficult :-) - I'm trying to figure out how far away GitHub/BitBucket/GitLab are from meeting the principles _as-is_.

**Comment by danielskatz** [comment]
I don't think GitHub is set up (or really ever will be) to host sufficient metadata.

Just thinking about authors as one type of metadate, where would GitHub list them, and how would they be tied to specific releases (the things we are asking people to cite)?

**Comment by arfon** [comment]
> I don't think GitHub is set up (or really ever will be) to host sufficient metadata.

I would argue that's what the API is for?

**Comment by danielskatz** [comment]
I don't know which API you mean.

I think we say in the principles document that we want people to be able to cite software, and we know that there is some metadata that we need to have included in the citation.  Once a person goes to the location specified by the unique identifier in the citation, that metadata should be shown.

To me, this is what a landing page does.

**Comment by arfon** [comment]
> I don't know which API you mean.

I mean things like this - here are the changes between two releases of a package via the GitHub API: https://api.github.com/repos/github/linguist/compare/v4.8.5...v4.8.6

> Once a person goes to the location specified by the unique identifier in the citation, that metadata should be shown.
> 
> To me, this is what a landing page does.

👍 ok fair enough.

**Comment by timclark** [comment]
I think it is unlikely that GitHub or BitBucket meet the criteria today, as-is - same is likely true for various data repositories. This is a new set of requirements and you would certainly expect that every player in the ecosystem will have to adapt and change to make it work. So there needs to be a discussion. 

Best

## Tim

Timothy Clark, Ph.D.
Assistant Professor of Neurology, Harvard Medical School
Director of Informatics, MassGeneral Institute for Neurodegenerative Disease
Computer Scientist, Massachusetts General Hospital 
co-Director, Data and Statistics Core, Massachusetts Alzheimer Disease Research Center
website: http://mindinformatics.org http://mindinformatics.org/ mobile: +1 617-947-7098 fax: +1 617-213-5418
ORCID ID: 0000-0003-4060-7360

**Comment by timclark** [comment]
Right

**Comment by arfon** [comment]
> I think it is unlikely that GitHub or BitBucket meet the criteria today, as-is - same is likely true for various data repositories. 

👍 that's a useful clarification. Thanks @timclark

**Comment by danielskatz** [comment]
I think we need to add some discussion about this, and in particular, mention some examples of how software can be published, such as via Zenodo - this has come up in my current Dagstuhl meeting

**Comment by matthewturk** [comment]
One possibility is to use the content negotiation that CrossRef provides to supply RDF/DOAP/etc information that includes all the appropriate metadata.  It could in principle even include additional formats if the DOI is registered through DataCite, since the DataCite schema 3.1 allows for `formats` to include MIME types, extensions, etc.  Having the landing page include the metadata seems necessary, but additionally providing the SCWG metadata in an additional format supplied and/or embedded in additional content negotiable formats seems quite nice as well.

**Comment by kyleniemeyer** [comment]
After discussion with @arfon and @danielskatz, I drafted a new subsection addressing this issue via 2a647eb.
